# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(463, 202)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.frame_count_label = QtWidgets.QLabel(self.centralwidget)
        self.frame_count_label.setObjectName("frame_count_label")
        self.horizontalLayout_2.addWidget(self.frame_count_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.movie_slider = QtWidgets.QSlider(self.centralwidget)
        self.movie_slider.setPageStep(1)
        self.movie_slider.setOrientation(QtCore.Qt.Horizontal)
        self.movie_slider.setObjectName("movie_slider")
        self.verticalLayout.addWidget(self.movie_slider)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnOpen = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpen.setObjectName("btnOpen")
        self.horizontalLayout.addWidget(self.btnOpen)
        self.btnPlayPause = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlayPause.setObjectName("btnPlayPause")
        self.horizontalLayout.addWidget(self.btnPlayPause)
        self.btnFrameBack = QtWidgets.QPushButton(self.centralwidget)
        self.btnFrameBack.setObjectName("btnFrameBack")
        self.horizontalLayout.addWidget(self.btnFrameBack)
        self.btnFrameForward = QtWidgets.QPushButton(self.centralwidget)
        self.btnFrameForward.setObjectName("btnFrameForward")
        self.horizontalLayout.addWidget(self.btnFrameForward)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenNI2 ONI player"))
        self.label.setText(_translate("MainWindow", "Индекс фрейма:"))
        self.frame_count_label.setText(_translate("MainWindow", "0"))
        self.btnOpen.setText(_translate("MainWindow", "Открыть файл..."))
        self.btnPlayPause.setText(_translate("MainWindow", "Пауза/Продолжить"))
        self.btnFrameBack.setText(_translate("MainWindow", "<< Кадр назад"))
        self.btnFrameForward.setText(_translate("MainWindow", "Кадр вперед >>"))
